# Generated by Django 3.1.1 on 2020-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20200923_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='places',
            name='location',
        ),
        migrations.AddField(
            model_name='places',
            name='lat',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AddField(
            model_name='places',
            name='lon',
            field=models.FloatField(default=0.0, max_length=20),
        ),
    ]
